### PR TITLE
Fix the cgi handler for uploading new espfs images because it kept timing out

### PR DESCRIPTION
**Pull request by bjpirt**
I've also added a check for the size of the image and the ability to return an error from CGI. This is now working nice and reliably for me and uploading the new image is a lot quicker and easier than using a serial connection.

@spritetm could you take a look at this and see if you fancy merging to your master please?

@billprozac thought you might be interested in this too - the initial loop for erasing memory was causing the WDT to reset for me so this only does it when we move into a new page

### CODE REVIEW

**Comment by Spritetm** [comment]
Not as is. Few points:
- I dislike the addition of  HTTPD_CGI_ERROR. In my eyes, conceptually CGI handlers can't exit with an error: they should in all cases output a valid HTTP header/body. I understand the use case for a conceptually non-warranted but practical error return which generates the error header/body in the httpd code, but I think this will promote non-descriptive generic errors. Not doing this will force the programmer to think up the correct http return code and body, which is a good thing.
- I didn't catch this before: I see you using numeric constants for the flash page/sector size. Doesn't the SDK have defines for that somewhere?
- Also, if we're going to expand on this concept, it may be time to pull all the code out to a separate file, like I did with cgiwifi.c.

**Comment by bjpirt** [comment]
To your points:

1) I was following your example of the 404 error :-) If we're having the cgi handlers fully responsible for all headers / body then I'm fine with that, but we should probably refactor that 404 into httpdespfs.c as well (maybe also rename to cgiespfs.c ?) - I'll pull the 500 response out for now and we can refactor the other stuff later if you agree

2) I was reusing the one that you defined for the start of the ESPFS, and added one for the size - I'm not sure where these are defined in the SDK though.

3) Agreed - how does cgiupgrade.c sound?

**Comment by bjpirt** [comment]
@Spritetm One more thought - I could put the 404 and 500 errors into functions which could then be called from elsewhere to save on duplication - what do you think?

**Comment by Spritetm** [comment]
1. I think you mis-understand the use of the HTTPD_CGI_NOTFOUND constant. A CGI function returning that doesn't imply that the http server should return a 404, it just implies the CGI function can't do anything with the URL it's passed: the web server will have to try the next one in the list. It's true that esphttpd will return a 404 if it has nothing that can handle the URL, but that's more like a side effect / fallback function  than the intended use of HTTPD_CGI_NOTFOUND. Truth be told, it may be better to explicitly handle that by writing a 404 cgi function.

2. I don't mean those ones, I mainly mean the 4096 and 0x1000 in eg the 'for (x=0; x<flashSize; x+=4096){ 
- spi_flash_erase_sector((flashOff+x)/0x1000);' - lines.

3. I'd rather have a reference to 'flash' in the name - 'cgiflash.c' or something would work, mainly because 'upgrade' is something that can be interpreted wrongly (you can also upgrade an http connection, for example).

Also, yes, if you can do it in a handily callable function like httpdReturnError(conn, 404, "File Not Found) it's probably a nice addition.

**Comment by bjpirt** [comment]
1. sounds good - will refactor to put 500 response into the cgi function and then we can pull out into a utility function (httpdReturnError) and refactor the 404s too

2. I see - looks like the sector size is defined in spi_flash.h so I'll use that instead

3. cgiflash.c is good for me - I'll move it into that

**Comment by bjpirt** [comment]
@spritetm just pushed changes that reflect the above - how does that look now?

**Comment by Spritetm** [comment]
Looks good. Just a nitpick - the comment at the start of the new file isn't really to the point anymore. I also notice I'm using magic constants in the flash read function - case of 'do as I say, not as I do' I guess :) I'll merge the modifications in main when i arrive at home; if you want you can fix the comment before that, if not I'll whip something up.

**Comment by bjpirt** [comment]
Well spotted - have updated the comment now and pushed again

**Comment by Spritetm** [comment]
Check, I've merged it.

**Comment by bjpirt** [comment]
Great, thanks!

**Pull request closed without merging**
